// src/App.tsx
import { ChangeEvent, useState } from "react";
import { CircleAlert, CircleCheckBig, Info, Loader, LogOut, Search } from "lucide-react";
import { useDebounceCallback } from "usehooks-ts";
import { Toaster } from "sonner";
import { useSupabase } from "./Supabase"
import { contactsTags, Tag } from "./tags";
import { Chips } from "./components/Chips";
import Contacts from "./Contacts";
import Auth from "./Auth";

export type Search = {terms?: string, tags?: Tag[]};

export default function App() {

    const { supabase, session } = useSupabase();
    
    const [search, setSearch] = useState<Search>({});

    const searchTerms = useDebounceCallback(terms => setSearch(current => ({...current, terms})), 500);

    return <>
        {session && <div className="max-w-screen-xl mx-auto my-8 px-8">
            <nav className="flex flex-row justify-between items-center w-full mb-8">
                <div className="relative whitespace-nowrap">
                    <div className="font-loubottin text-4xl text-oultine text-slate-950">Loup Bottin</div>
                    <div className="relative font-loubottin text-4xl text-primary-400">Loup Bottin</div>
                </div>
                <button className="button-ghost" onClick={() => supabase.auth.signOut()}>
                    <span className="hidden sm:inline">Sign Out </span><LogOut />
                </button>
            </nav>

            <div className="mb-8">
                <div className="relative flex flex-wrap pl-11 pr-3 rounded-2xl transition-all bg-slate-800 outline outline-2 outline-slate-700
                    focus-within:outline-primary-700">
                    
                    <input type="search" placeholder="Rechercher dans les contacts..." defaultValue={search.terms} onChange={e => searchTerms(e.target.value)} 
                        className="flex-1 px-0 py-2 min-w-64 peer !bg-transparent !outline-none" />
                    
                    <Search className="absolute top-2 left-3 transition-colors text-slate-600 peer-focus:text-primary-700" />
                    
                    <div className="flex items-center gap-2 ml-auto my-2">
                        {Object.entries(contactsTags)?.map(([tagName, {icon: Icon, className}]) => {
                            return <Chips key={tagName} name="tags" className={className} 
                                onChange={(e: ChangeEvent<HTMLInputElement>) => setSearch(current => {
                                
                                    current.tags = (current.tags ?? []).filter(i => i !== tagName);
                            
                                    if(e.target.checked)
                                        current.tags = [...current.tags, tagName as Tag];

                                    if(current.tags.length === 0)
                                        delete current.tags;

                                    return {...current};
                                })}><Icon /> {tagName}</Chips>
                        })}
                    </div>
                </div>
            </div>
            <Contacts search={search} />
        </div>}
        <Auth />
        <Toaster position="bottom-center"
            icons={{
                info: <Info />,
                error: <CircleAlert />,
                warning: <CircleAlert />,
                success: <CircleCheckBig />,
                loading: <Loader className="animate-loader" />
            }}
            toastOptions={{
                classNames: {
                    toast: "p-6 bg-slate-100 pointer-events-auto",
                    icon: "size-6",
                    error: "text-red-500",
                    warning: "text-amber-500",
                    success: "text-primary-500",
                    closeButton: "button-toast-close"
                }
            }}
        />
    </>
}

// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'loubottin';
}

<ng-template #signInTemplate>
    <app-signin></app-signin>
</ng-template>

<ng-container [ngSwitch]="page">

    <app-update-password *ngSwitchCase="'updatePassword'"></app-update-password>

    <ng-container *ngSwitchDefault>
        <ng-container *ngIf="session; else signInTemplate">
            <div class="w-full max-w-screen-xl px-8 mx-auto mt-8 flex items-center justify-between">
                <h1 class="text-loubottin-400">Loup Bottin</h1>
                <button class="button-warn" (click)="signOut()" *ngIf="session">
                    Sign Out
                    <lucide-icon name="log-out"></lucide-icon>
                </button>
            </div>
            
            <div [formGroup]="searchForm" class="w-full my-24 sticky -top-1 pt-9 pb-8 z-40 bg-slate-900/75 backdrop-blur-xl">
                <div class="max-w-screen-xl flex flex-col mx-auto px-8">
                    <div class="relative">
                        <input type="text" placeholder="Rechercher" formControlName="terms" (ngModelChange)="searchForm.updateValueAndValidity()" 
                                class="px-12 w-full rounded-full shadow-lg peer" />
                        <lucide-icon name="search" ngClass="absolute h-full left-4 text-slate-500 peer-focus:text-loubottin-500"></lucide-icon>
                        <button class="absolute right-0.5 top-0.5 button-icon" *ngIf="searchForm.get('terms')?.value" (click)="searchForm.get('terms')?.reset()">
                            <lucide-icon name="x"></lucide-icon>
                        </button>
                    </div>
                    <small class="text-slate-500 place-self-end mt-2">
                        Appuyez sur <span class="text-white bg-slate-700 px-1.5 rounded-md text-base">⏎</span> pour lancer la recheche
                    </small>
                    <div class="flex flex-row flex-wrap items-center gap-4 mt-4">
                        <span class="text-slate-400">Tags</span>
                        <button *ngFor="let tag of tags | keyvalue" class="button-flat button-filter" [ngClass]="{
                            'active': searchForm.get('tags')?.value?.includes($any(tag.key))
                        }" (click)="toggleTagsFilter($any(tag.key))">
                            <lucide-icon [name]="searchForm.get('tags')?.value?.includes($any(tag.key)) ? 'check-square' : tag.value.icon"></lucide-icon>
                            {{tag.key}}
                        </button>
                    </div>
                </div>
            </div>
            
            <div class="w-full max-w-screen-xl px-8 mx-auto my-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                <div *ngIf="!contacts" class="contact flex flex-row gap-2 md:col-span-2 lg:col-span-3 xl:col-span-4">
                    <lucide-icon name="loader" ngClass="animate-spin"></lucide-icon>
                    Recherche des contacts
                </div>
                <div *ngIf="contacts?.length === 0" class="contact  md:col-span-2 lg:col-span-3 xl:col-span-4">
                    Aucun résultat
                </div>
                <div *ngFor="let item of contacts; trackBy: trackById" class="contact">
                    <div class="flex items-start gap-2">
                        <lucide-icon *ngFor="let tag of item.tags" [name]="tags ? tags[tag].icon : ''" [ngClass]="{
                            'text-loubottin-400': tag === 'salarié',
                            'text-pink-400': tag === 'établissement'
                        }"></lucide-icon>
                        <div class="text-xl mb-2">{{item.name}}</div>
                    </div>
                    <div class="flex items-start gap-2" *ngIf="item.address">
                        <lucide-icon name="map-pin" ngClass="text-slate-500"></lucide-icon>
                        <div class="text-slate-400">{{item.address}}</div>
                    </div>
                    <div class="flex items-start gap-2" *ngIf="item.mobile">
                        <lucide-icon name="smartphone" ngClass="text-slate-500" ></lucide-icon>
                        <div class="text-slate-400">{{item.mobile}}</div>
                    </div>
                    <div class="flex items-start gap-2" *ngIf="item.phone">
                        <lucide-icon name="phone" ngClass="text-slate-500" ></lucide-icon>
                        <div class="text-slate-400">{{item.phone}}</div>
                    </div>
                    <div class="flex-1"></div>
                </div>
            </div>
        </ng-container>
    </ng-container>
</ng-container>

<div class="fixed w-full max-w-md bottom-0 left-1/2 -translate-x-1/2 z-50 mb-8">
    <div *ngFor="let notification of notifications; let index = index; trackBy: trackById" class="overflow-visible mb-4" @notification>
        <div class="relative px-8 py-4 flex flex-row items-stretch gap-4 rounded-2xl shadow-xl shadow-slate-950 backdrop-blur-xl bg-slate-800/75" 
            [ngClass]="{
                'text-loubottin-400': notification.state === 'success',
                'text-red-400': notification.state === 'warn'
            }"
            [ngStyle]="{zIndex: 50 + index}">
            <div *ngIf="notification.icon || notification.state" class="max-h-12 flex items-center flex-none">
                <lucide-icon [name]="notification.icon ?? (
                    notification.state === 'pending' ? 'loader' : (
                    notification.state === 'success' ? 'check' : (
                    notification.state === 'warn' ? 'alert-triangle' : '')))" [ngClass]="{

                    'text-slate-500 animate-spin': notification.state === 'pending',
                    'text-loubottin-400': notification.state === 'success',
                    'text-red-400': notification.state === 'warn'
                }"></lucide-icon>
            </div>
            <div class="flex-1 self-center">
                {{notification.message}}
            </div>
            <div  class="max-h-12 flex items-center flex-none -mr-4">
                <button *ngIf="notification.state !== 'pending'" class="button-icon" (click)="notification.close()">
                    <lucide-icon name="x"></lucide-icon>
                </button>
            </div>
        </div>
    </div>
</div>
